// Run the procedural generators as a Node unit fixture; no browser or rendered-game claims.
const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(require('path').join(__dirname,'../../public/3d/index.html'),'utf8');
const code=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)].filter(m=>!(/src=|module|importmap|application\//.test(m[1]))).map(m=>m[2]).join('\n');
function stub(){let proxy;const fn=function(){return proxy};proxy=new Proxy(fn,{get(t,k){if(k===Symbol.toPrimitive)return()=>0;if(k===Symbol.iterator)return function*(){};if(k==='then')return undefined;if(k==='length')return 0;if(k==='style'||k==='classList')return proxy;if(k==='getBoundingClientRect')return()=>({width:1280,height:720,left:0,top:0});if(k==='getParameter')return()=>4096;if(k==='getShaderParameter'||k==='getProgramParameter')return()=>true;if(k==='getContext')return()=>proxy;if(k==='querySelectorAll')return()=>[];return k in t?t[k]:proxy},set(t,k,v){t[k]=v;return true}});return proxy}
const nodes=new Map(),document=stub();document.getElementById=id=>{if(!nodes.has(id))nodes.set(id,stub());return nodes.get(id)};document.createElement=()=>stub();document.querySelectorAll=()=>[];document.fonts={ready:Promise.resolve()};
const context={console,document,location:{search:'?mute=1',hostname:'localhost',protocol:'http:',href:'http://localhost/'},navigator:{userAgent:'Node unit fixture',getGamepads:()=>[]},localStorage:{getItem:()=>null,setItem(){},removeItem(){}},performance:{now:()=>0},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},requestAnimationFrame:()=>0,cancelAnimationFrame(){},addEventListener(){},innerWidth:1280,innerHeight:720,devicePixelRatio:1,Image:class{},URLSearchParams,URL,fetch:async()=>({ok:false,json:async()=>({})}),Math,Date,Map,Set,Float32Array,Uint16Array,Uint8Array,Uint32Array,ArrayBuffer,TextEncoder,TextDecoder,atob,btoa};context.window=context;context.self=context;context.window.matchMedia=()=>({matches:false,addEventListener(){}});vm.createContext(context);vm.runInContext(code,context,{timeout:10000});
vm.runInContext(`__BF3.meta.classId='warrior';__BF3.meta.classUnlocked={warrior:true};__BF3.loadMode('rl');`,context);

const out=[];
for(let zone=0;zone<8;zone++)for(const area of [0,1,-1]){
const d=vm.runInContext(`(()=>{const a=__BF3;a.enterZone(${zone});const g=a.G;g.area=${area};a.loadArea();const step=30,k=(x,z)=>x+','+z,sx=Math.round(g.p.x/step),sz=Math.round(g.p.z/step),height=(x,z)=>a.surfaceHeightAt(x*step,z*step,14);const seen=new Map([[k(sx,sz),height(sx,sz)]]),q=[[sx,sz]];
for(let i=0;i<q.length&&i<50000;i++){const [x,z]=q[i],h=seen.get(k(x,z));for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]])for(let n=1;n<=4;n++){const nx=x+dx*n,nz=z+dz*n,key=k(nx,nz);if(seen.has(key))break;const nh=height(nx,nz);if(!Number.isFinite(nh))continue;if(nh-h>50)break;seen.set(key,nh);q.push([nx,nz]);break;}}
const reachable=p=>{const x=Math.round(p.x/step),z=Math.round(p.z/step),y=p.y??p.y0??0;return [0,-1,1].some(dx=>[0,-1,1].some(dz=>seen.has(k(x+dx,z+dz))&&Math.abs(seen.get(k(x+dx,z+dz))-y)<=25));};
const targets=[{...g.portalPos,id:'portal'},g.waystone&&{...g.waystone,id:'waystone'},g.secret&&{...g.secret,id:'secret'},...g.qmarks.map(p=>({...p,id:p.q})),...g.chests.map(p=>({...p,id:'chest'})),...g.pickups.filter(p=>p.questItem||p.localItem).map(p=>({...p,id:p.questItem?.id||p.localItem.id}))].filter(Boolean);
return JSON.stringify({zone:${zone},area:${area},cells:seen.size,targets:targets.length,unreachable:targets.filter(p=>!reachable(p)).map(p=>({id:p.id,x:p.x,y:p.y??p.y0,z:p.z})),boss:g.boss&&{type:g.boss.type,hp:g.boss.hp},generator:g._scapeTable});})()`,context,{timeout:30000});out.push(JSON.parse(d));}
if(process.argv[2])fs.writeFileSync(process.argv[2],JSON.stringify(out,null,2));if(out.some(r=>r.unreachable.length))throw Error('Campaign target unreachable');console.log(JSON.stringify(out));
