// Run the procedural generators as a Node unit fixture; no browser or rendered-game claims.
const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(require('path').join(__dirname,'../../public/3d/index.html'),'utf8');
const code=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)].filter(m=>!(/src=|module|importmap|application\//.test(m[1]))).map(m=>m[2]).join('\n');
function stub(){let proxy;const fn=function(){return proxy};proxy=new Proxy(fn,{get(t,k){if(k===Symbol.toPrimitive)return()=>0;if(k===Symbol.iterator)return function*(){};if(k==='then')return undefined;if(k==='length')return 0;if(k==='style'||k==='classList')return proxy;if(k==='getBoundingClientRect')return()=>({width:1280,height:720,left:0,top:0});if(k==='getParameter')return()=>4096;if(k==='getShaderParameter'||k==='getProgramParameter')return()=>true;if(k==='getContext')return()=>proxy;if(k==='querySelectorAll')return()=>[];return k in t?t[k]:proxy},set(t,k,v){t[k]=v;return true}});return proxy}
const nodes=new Map(),document=stub();document.getElementById=id=>{if(!nodes.has(id))nodes.set(id,stub());return nodes.get(id)};document.createElement=()=>stub();document.querySelectorAll=()=>[];document.fonts={ready:Promise.resolve()};
const context={console,document,location:{search:'?mute=1',hostname:'localhost',protocol:'http:',href:'http://localhost/'},navigator:{userAgent:'Node unit fixture',getGamepads:()=>[]},localStorage:{getItem:()=>null,setItem(){},removeItem(){}},performance:{now:()=>0},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},requestAnimationFrame:()=>0,cancelAnimationFrame(){},addEventListener(){},innerWidth:1280,innerHeight:720,devicePixelRatio:1,Image:class{},URLSearchParams,URL,fetch:async()=>({ok:false,json:async()=>({})}),Math,Date,Map,Set,Float32Array,Uint16Array,Uint8Array,Uint32Array,ArrayBuffer,TextEncoder,TextDecoder,atob,btoa};context.window=context;context.self=context;context.window.matchMedia=()=>({matches:false,addEventListener(){}});vm.createContext(context);vm.runInContext(code,context,{timeout:10000});
vm.runInContext(`__BF3.meta.classId='warrior';__BF3.meta.classUnlocked={warrior:true};__BF3.loadMode('rl');`,context);

const out=[];
for(let zone=0;zone<8;zone++)for(let area=0;area<2;area++){
const r=vm.runInContext(`(()=>{const a=__BF3;a.enterZone(${zone});const g=a.G;g.area=${area};a.loadArea();a.meta.camMode='far';a.meta.autoAttack=false;g.enemies=[];g.dens=[];g.pickups=[];g.qmarks=[];g.portal=null;g.waystone=null;g.secret=null;g.haz=null;g.p.invuln=999999;g.healpads=[];g.chests=[];g.optionalMissions=[];const out=[];
for(const edge of g.campaignLayout.edges){for(const reverse of [false,true]){const ns=g.campaignLayout.nodes,pts=[ns[edge.a],...edge.points,ns[edge.b]];if(reverse)pts.reverse();const start=pts[0];Object.assign(g.p,{x:start.x,z:start.z,y:start.y,vx:0,vz:0,vy:0,onGround:true,recoverT:0});let steps=0,fail=null;
for(const p of pts.slice(1)){let n=0;while(Math.hypot(g.p.x-p.x,g.p.z-p.z)>16&&n++<360){const dx=p.x-g.p.x,dz=p.z-g.p.z,L=Math.hypot(dx,dz);a.input.jx=dx/L;a.input.jz=dz/L;a.update(1/60);steps++;if(g.p.y< -20){fail='fell';break;}}if(n>=360){fail={stuck:[g.p.x,g.p.y,g.p.z],goal:p};break;}if(fail)break;}
a.input.jx=0;a.input.jz=0;out.push({edge:[edge.a,edge.b],reverse,steps,fail});}}
return JSON.stringify({zone:${zone},area:${area},routes:out});})()`,context,{timeout:120000});out.push(JSON.parse(r));console.log(zone,area,JSON.parse(r).routes.filter(x=>x.fail));}
if(process.argv[2])fs.writeFileSync(process.argv[2],JSON.stringify(out,null,2));if(out.some(r=>r.routes.some(e=>e.fail)))throw Error('Campaign walk failed');
