"""Build the public, source-grounded campaign review. No game state is changed."""
from pathlib import Path
import json, html, hashlib

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / 'docs/design/campaign-audit'
PUB = ROOT / 'public/design/campaign-audit'
PUB.mkdir(parents=True, exist_ok=True)
esc = html.escape
# name, source module, current objective, keep, concern, proposed direction
AREAS = [
('Homefields','index.html','Help Thomas and Mara, restore the mill crossing, open the wagon gate.',
 'The family stakes, healing introduction and water → jam → bridge cause-and-effect.',
 'Supplies, several mill interactions and a return to Mara compete with the first-time learning load. More objects alone will not improve this opening.',
 'Make home, medical station, mill and escape gate visible parts of one village. Put dressings in a believable damaged home; roots at the stream. Let the mill reveal the next route. Keep Thomas and Mara central.'),
('Black Woods','index.html','Meet Lewis, silence the signal by ground crank or upper cable, reach the shelter.',
 'Two approaches to the signal and the captive/dog rescue opportunities.',
 'The upper route must be readable as a deliberate alternative, not anonymous green platforms. Existing objective alternatives deserve more prominence than additional errands.',
 'Use the signal tower as a persistent landmark. Ground combat and canopy parkour converge at it. Put rescue pens beside the Legion camp, with a visible safe path toward the shelter.'),
('Winding Cliffs','hollow-cliffs.js','Follow prisoner-transport tracks, repair the freight crossing, bypass or fight the lookout, descend.',
 'Evidence leads the player onward; an upper rope can avoid the lookout fight.',
 'A weights/bridge objective risks reading as another arbitrary interaction gate unless the broken freight route and load are plainly visible.',
 'Build around a wrecked transport on a narrow trade ledge. Show the destination across the gap before the repair. Make the optional climber loop teach the upper approach.'),
('Lost Canyon','lost-canyon.js','Enter by papers, force or upper route; free two groups, stop the alarm and open escape.',
 'Multiple entry methods, alarm control and rescuing an enslaved population.',
 'Two prisoner groups can feel like repeating the same switch unless their positions create different tactical problems.',
 'One group sits beneath the lookout; another is exposed to the alarm route. Let reconnaissance reveal both. Rescue changes who occupies the yard; optional patrol hunting stays in a clearly marked reinforcement area.'),
('Broken Walls','broken-walls.js','Silence the arrow post, open the side gate, ring the breach bell, hold the breach, enter the prison.',
 'A timed defense followed by key-or-battlement-wheel entry already changes the activity.',
 'A timer plus remaining-enemy requirement can be unclear. Felix’s tool return needs a credible workshop and a worthwhile shortcut/reward.',
 'Place the breach at a visibly damaged wall with defenders behind it and attackers outside. Show both timer and remaining attackers. Put the locksmith’s chamber on a distinct optional battlement loop.'),
('The Dungeons','prison-dungeons.js','Locate cells, free prisoners, recover papers, balance the lift and transfer the group.',
 'Prisoner rescue, seized evidence and the optional stolen-locket restitution.',
 'The authored service route climbs from the lower ring toward the upper exit, while Walter mentions eastern service stairs. This weakens the lift’s necessity; a quest bypass itself has not been demonstrated.',
 'Test the isolated Keep beta before replacing this map. Its separate maintenance route is usable by the player while the wounded prisoners need the lift. Preserve that physical distinction in any final version.'),
('Snowbound Peaks','snowbound-peaks.js','Find Heath, fetch and return the heater part, decode the signal carving and enter the cave.',
 'Mountain ascent, wind shelter, a distant cave goal and optional buried-camp reward.',
 'The heater has a valid purpose—thawing the winch—but the required return trip slows the ascent. The three-choice carving is mainly clue recognition.',
 'Proposed next prototype: repair the frozen crossing on the forward route, then navigate wind and an aligned signal beam. Keep the old lift as an optional shortcut loop. See the revised Frostfell maps below; existing sequences are not approved to carry forward unchanged.'),
('Deep Ice Caves','deep-ice-caves.js','Follow pages, release Ellis, fetch his notes and return, build the ice crossing, confront three officers.',
 'Ellis is captured just before transport. The water-and-ice setting suits a physical puzzle; Hugo’s rope rescue already moves him along a route. The current three-control crossing is not yet sufficient variety.',
 'The sealed-pack return repeats the mountain’s errand. Three nearby Fill/Freeze/Drain controls still invite combination guessing; changing water height in code does not by itself make the experience satisfying.',
 'Rescue Ellis first; recover his records on the escape route ahead. Show the water basin and exit from the lab. Replace the three-control puzzle with spatial water manipulation. Keep the three officers as a coordinated exit fight and Hugo’s rescue optional.'),
('Iron Halls','iron-halls.js','Reach the workers, find Jack, retrieve insulated handles, operate machinery and bridge the cart gap.',
 'The forge supplies the Legion; machinery and trapped workers belong here.',
 'Another required component retrieval and NPC return follows Frostfell. Repeated dialogue approval can make visibly operable machinery feel artificial.',
 'Make the receiving yard, tool station, production line and furnace form one readable industrial process. Recover handles while crossing the active line; use them at the machine, with Jack providing optional help.'),
('Great Furnace','great-furnace.js','Evacuate workers, cool the crossing, find seized writings, consult Martin, face the colossus.',
 'Quiet/loud evacuation paths, real cooling controls and written evidence that points toward Sunspire.',
 'Many successive flags can hide the simple purpose: get workers out, shut production down and recover the records. The cooling gauge must be visible from its controls.',
 'Organize around the furnace chamber and a safe worker exit. Show pipes from tank to channel. Place the command office overlooking the operation; the writings—not a convenient NPC rumor—reveal the secret destination.'),
('Shipwreck Shore','shipwreck-shore.js','Recover and install rudder, sail and rope, then steer the repaired ship across.',
 'This fetch objective has a clear physical outcome and leads into a distinct playable crossing.',
 'Three components still risk three identical pickups. Plenty of loot cannot substitute for different retrieval challenges.',
 'Rudder in a flooded hull, sail reached across rigging, rope taken from a guarded salvage winch. Show each installed piece on the ship. Preserve the crossing and the captain’s optional personal story.'),
('Thunder Cliffs','thunder-cliffs.js','Repair the cargo lift, release its catch via the eastern steps, inspect a shackle and reach the hydra.',
 'Wind traversal and the discarded shackle prepare the merciful chain-breaking hydra encounter.',
 'The steps already reach the lift’s middle ledge. This can be a legitimate shortcut, but its mandatory repair needs a clearer reason than reaching a place the stairs already reach.',
 'Treat the lift as an optional return shortcut unless a necessary cargo purpose is established. Make the hydra’s chains anchor into the ascent architecture, with safe ledges and distinct routes to each chain.'),
('Palace Courtyard','palace-courtyard.js','Remove a clamp, run the waterwheel, release balcony locks and direct sunlight into the library door.',
 'A visible reflected-light path could distinguish Sunspire, provided aiming and occlusion are readable from the play camera.',
 'A clamp, wheel, two locks and mirrors can become too many serial gates before the payoff.',
 'Use the courtyard fountain and one visible light path as the organizing structure. Let the waterwheel restore the mirror mechanism; reserve one balcony for optional mastery instead of another compulsory latch.'),
('Sky Library','sky-library.js','Enter by Hugh or the lower passage, find Legion orders, open the reading-hall seal and face the guardian.',
 'Navigable shelves, preserving records and the sacred orb after the guardian. Linked three-control rotation is still a combination puzzle until the player reasons about the physical route.',
 'A giant library becomes generic if its paths are just corridors decorated with shelves. The orb’s revelation must not spoil Ian or the final cut.',
 'Make shelves carry navigable bridges and change sightlines into the sacred chamber. Let the player see inaccessible knowledge above them. Place optional record rescue away from the critical route with an obvious return loop.'),
('Castle Gates','castle-gates.js','Repair the approach, acquire disguise and papers or confront Cross, then enter the castle.',
 'Disguise plus dialogue, with a difficult combat fallback, is a signature campaign payoff.',
 'Two bridge catches before infiltration may dilute the unique encounter. Repeated wheel operation adds little here.',
 'Center the layout on reconnaissance, an occupied repair yard and the inspection lane. Place useful orders where the player can observe guards working. Failure triggers the existing combat route; it must not trap the quest.'),
('Long Ascent','long-ascent.js','Release lower and upper catches, climb broken flights, defeat summit guards and enter the throne room.',
 'The huge spiral climb, exposed gaps and the final approach to the King.',
 'The route hint currently repeats its broken-flight explanation. Catch operations need visible architectural consequences. Freed workers are repositioned rather than shown making a full escape.',
 'Keep the tower’s scale but break ascent into clear combat, traversal and quiet-view sections. Show bolts retracting where catches matter. Use a short safe departure for optional prisoners; avoid implying an escort that was not simulated.'),
]

def source_info(module):
    p=ROOT/'public/3d'/module
    text=p.read_text(encoding='utf-8-sig')
    tokens=['function briarQuest','function quest','function sync','const paths']
    anchors={t:text[:text.index(t)].count('\n')+1 for t in tokens if t in text}
    return dict(path=str(p.relative_to(ROOT)).replace('\\','/'),sha256=hashlib.sha256(p.read_bytes()).hexdigest(),anchors=anchors)

inventory=json.loads((DOC/'runtime-inventory.json').read_text(encoding='utf-8'))
assert len(inventory['areas'])==16
assert not any(a['invalidCoordinates'] for a in inventory['areas'])
review=[]
for i,(name,module,current,keep,concern,proposal) in enumerate(AREAS):
    review.append(dict(name=name,current=current,keep=keep,concern=concern,proposal=proposal,source=source_info(module),runtimeCounts=inventory['areas'][i]['counts']))
(DOC/'review.json').write_text(json.dumps({'status':'Proposals, not implemented campaign changes','sourceCommit':'1f46dd0','areas':review},indent=2),encoding='utf-8')

CSS='''*{box-sizing:border-box}body{margin:0;background:#111c25;color:#e8eef1;font:17px/1.6 system-ui,sans-serif}main{max-width:1050px;margin:auto;padding:24px}h1{font-size:clamp(28px,5vw,46px);line-height:1.12}h2{margin-top:34px;color:#f3ca83}h3{color:#b7e1e9}a{color:#91dbe8}p{max-width:78ch}.tag{color:#f3ca83;font-size:14px;text-transform:uppercase;letter-spacing:.1em}.box,details{background:#1b2b37;border:1px solid #405462;border-radius:12px;padding:18px;margin:14px 0}summary{cursor:pointer;font-weight:700}small{color:#b6c6d0}img{display:block;width:100%;height:auto;background:#15232e;border-radius:12px}nav{display:flex;gap:14px;flex-wrap:wrap}li{margin:9px 0}code{overflow-wrap:anywhere}.two{display:grid;grid-template-columns:1fr 1fr;gap:16px}@media(max-width:650px){main{padding:16px}.two{grid-template-columns:1fr}}'''
cards=''
for r in review:
    src=r['source']; anchor=next(iter(src['anchors'].values()),1)
    cards+=f'''<details><summary>{esc(r['name'])}</summary><p><b>Current:</b> {esc(r['current'])}</p><p><b>Keep:</b> {esc(r['keep'])}</p><p><b>Concern:</b> {esc(r['concern'])}</p><p><b>Proposed:</b> {esc(r['proposal'])}</p><small>Reviewed {esc(src['path'])}, starting around line {anchor}. Initial runtime: {r['runtimeCounts']['enemies']} enemies, {r['runtimeCounts']['storyObjects']} story objects. These counts do not measure quality or total respawns.</small></details>'''

INTRO='''<nav><a href="/3d/">← Bladefall</a><a href="/design/ruined-keep-beta/">Keep beta plan</a><a href="#frostfell">Frostfell maps ↓</a></nav>
<p class="tag">Design review · October 5, 2026 · proposals only</p><h1>Make the journey make sense.</h1>
<p>Reviewed all 16 campaign parts. The next step is stronger connections between geography, objectives and rewards—not simply adding more objects.</p>
<div class="box"><b>The short version</b><ul><li>Test the isolated Ruined Keep beta before rebuilding another playable level.</li><li>Keep distinct experiences such as ship steering, disguise and tower traversal. Rebuild button-combination puzzles around physical, visible problems.</li><li>Replace repeated component-return errands with objectives that carry you forward.</li><li>Use Frostfell to test a mountain approach, urgent rescue and spatial water manipulation—not another three-button sequence.</li></ul><strong>No playable campaign maps changed in this pass.</strong></div>
<h2>What the code actually shows</h2><p><b>Confirmed:</b> the old prison has an ascending service route and dialogue mentioning stairs; the lift needs clearer necessity. Frostfell’s two halves both require a fetch-and-return. The tower hint repeats itself. Thunder Cliffs has stairs to its lift’s upper area, so the lift’s purpose needs clarification.</p>
<p><b>Design risks, not proven bugs:</b> too much travel between interactions, too many serial locks, weak reward visibility, and unclear safe routes for rescued people. These require observation in play, not a claim that a static audit has proved them.</p>
<p><b>Important correction:</b> different state machines and story labels do not establish puzzle variety. The player reports that many still feel like guessing three controls. Water, mirrors and shelves are useful themes, but their present execution must earn its place through visible interaction. Patrol hunts and alternative approaches are separate strengths.</p>
<h2>A different review standard</h2><p><b>The failure:</b> this audit initially credited different state logic and lore as evidence of different play. That was too generous. The user’s play experience—repetitive guessing and weak visual feedback—takes priority over those descriptions.</p><div class="box"><b>Before calling a puzzle ready</b><ol><li><b>Strip the names:</b> describe only what the player does. “Press three nearby controls until a crossing unlocks” is one family, whether the props are valves, bells or runes.</li><li><b>Compare the actions:</b> changing a code, palette or reward does not create a new interaction. State-setting toggles and order-entry buttons can both be the same experience of guessing a small combination.</li><li><b>Show the evidence:</b> record an uncut attempt from the normal game camera with the starting scene, player actions, visible consequences, a mistake and recovery. Teleporting or setting quest flags is not evidence of playability.</li><li><b>Try it without instructions:</b> temporarily hide the journal solution and explanatory toast. Can the scene support a reasonable prediction? Does each action communicate its result? If not, fix the physical presentation first.</li><li><b>Build one example:</b> prove one compact interaction before expanding the level or duplicating its mechanism. Maps establish intended relationships; they do not establish enjoyment.</li><li><b>Human gate:</b> user playtesting decides whether the prototype is satisfying and sufficiently different. Automated checks establish correctness and safety only.</li></ol></div><p><b>Status of this packet:</b> code inspected and initial areas loaded; document layout checked. Campaign puzzles have not received new unassisted playthroughs or interaction recordings in this pass. Frostfell maps are proposals. No claim of proven fun, clarity or variety.</p>
<details><summary>Examples classified by the actual player action</summary><ul><li><b>Deep Ice Caves main crossing:</b> three nearby controls change water level, freeze state and drain state. The solver checks the target height. This is more than literal order matching in code, but still belongs to the small-console combination family in the reported experience.</li><li><b>Deep Ice Caves side channel:</b> three switches toggle a three-bit state; the accepted state is 5. A water-themed description does not establish a spatial routing experience.</li><li><b>Counterweight controls:</b> toggle a small set of numbered weights until a target is met. Different weight values do not justify treating each occurrence as a different puzzle.</li><li><b>Linked shelf controls:</b> each action rotates two stored states toward a target. Unless navigating the changing shelves is essential and readable, this remains another console configuration task.</li><li><b>Ship crossing:</b> continuously steer and react to hazards. This is a mechanically different action family, though difficulty and enjoyment still need playtesting.</li></ul><small>State logic: public/3d/story-state.js (waterworks, flowSwitch, counterweight, linkedRotate); placements and presentation: deep-ice-caves.js and sky-library.js. These examples are not a claim that every legacy JSON definition runs unchanged.</small></details><h2>Every campaign part</h2><p>Tap a name only if you want the evidence and proposed change.</p>'''

PLAN='''<section id="frostfell"><h2>Next proposal: Frostfell</h2><p>The player follows the lead about Ellis into a remote mountain laboratory. The Legion has just captured him. Rescue him before transport, recover his records, then escape through the ice caves. His work advances the investigation; Sunspire’s orb and the final cut remain later discoveries.</p>
<div class="box"><b>One sentence per half</b><p><strong>Peaks:</strong> reach the visible cave by restoring one frozen crossing and reading the mountain’s wind and light.</p><p><strong>Caves:</strong> interrupt a prisoner transfer, then change the water into a route through the mountain.</p></div>
<h3>Part 1 · Snowbound Peaks</h3><a href="peaks.svg"><img src="peaks.svg" alt="Proposed mountain route, with an optional old lift loop and a visible cave landmark"></a>
<ol><li><b>Foot of the mountain:</b> see the cave’s signal crown immediately. Fresh boot tracks and a dropped research page establish urgency. No new mandatory NPC greeting.</li><li><b>Heath’s shelter:</b> a short optional explanation points out the frozen crossing. Heath remains useful and believable. The repair hardware sits on the approach to the crossing, not behind the player.</li><li><b>Crossing winch:</b> move a shelter shutter to direct visible warm air onto its frozen brake. Ice visibly melts, then the player operates the winch. This proposed spatial interaction replaces the compulsory part-return loop; no new magical canon is required.</li><li><b>Wind traverse:</b> alternate sheltered rests with short exposed jumps. Flags and drifting snow show safe timing. Falling returns to a catch ledge with a short recovery route. Do not add a health drain merely for standing outside.</li><li><b>Signal crown:</b> align a reflector toward the cave marker visible across the slope. A beam confirms alignment. The result reveals a sheltered approach; it does not magically create unrelated terrain.</li><li><b>Cave approach:</b> scattered transport gear and an alert patrol show that the Legion got here first. A brief fight changes the pace before entering.</li></ol>
<p><b>Optional loop:</b> the abandoned lift house connects to a buried camp and a harder roof climb. Its loop rejoins on the near side of the required crossing, so it cannot bypass the winch. Restoring its lift opens a return shortcut within that lower loop. Keep the winter-cloak reward and the region’s shard hunt; an optional return loop is useful even when the main route avoids backtracking.</p>
<h3>Part 2 · Deep Ice Caves</h3><a href="caves.svg"><img src="caves.svg" alt="Proposed cave route from entrance to laboratory rescue, water basin, officer exit and optional rope rescue"></a>
<ol><li><b>Entrance overlook:</b> glimpse the laboratory below and the exit across the basin. Boot tracks and a guard’s call direct the player. Use geometry to explain the route before text.</li><li><b>Laboratory rescue:</b> interrupt guards preparing to move Ellis. Give the guards clear roles: one pressures the player, one protects the prisoner route. Do not invent a failure countdown that kills Ellis and blocks the campaign.</li><li><b>Records on the escape route:</b> Ellis identifies the confiscated pack ahead. Recover it while advancing toward the basin; his next conversation happens at the safe control ledge. Avoid carrying it back to an empty laboratory.</li><li><b>Ice crossing:</b> from the overlook, see the stream, floating platform, cold-air vent and far landing together. Move a physical channel to direct the visible stream onto a floating platform. Ride that platform as the water rises to a ledge. From there, move a cold-air shutter so its clearly visible freezing area overlaps a shallow side channel. Cross the resulting ice. Water outside that area keeps flowing. There is no hidden correct button order, no three-choice console and no success flag that simply spawns an unrelated bridge. Provide safe dry returns and a local reset if a platform gets stranded.</li><li><b>Traverse the result:</b> a short mandatory jump sequence tests the route the player created. Separate this from optional expert jumps; keep clear landing silhouettes and solid floors.</li><li><b>Exit officers:</b> retain the three-entity encounter. Give each a different spatial job rather than tripling one enemy. Let cover break ranged pressure and a broad center support melee dodges.</li></ol>
<p><b>Optional loop:</b> Hugo is stranded below the basin. A visible rescue frame, rope route and safe upper landing make the rescue understandable. A separate chiller branch provides a harder exploration reward. Neither should reset the main crossing or require repeating the laboratory fight.</p>
<h3>What makes these puzzles different?</h3><div class="box"><p><b>Judge the player’s action, not the story noun.</b> A bell order, rune order and valve order are the same family. Three toggles and three rotating symbols can still feel the same even when the math differs.</p><ul><li><b>Spatial manipulation:</b> move a channel or shutter; see its stream or freezing area move with it. The question is “where should this go?”</li><li><b>Traversal planning:</b> observe a moving platform, choose when to board and where to jump. The question is “how can I reach that ledge?”</li><li><b>Observation:</b> follow a light path through actual obstacles. The question is “what is blocking it?”</li><li><b>Combat application:</b> lure a clearly telegraphed charge into a cracked barrier. The question is “how can this enemy help open my route?” Reserve this as a later candidate, not an extra mandatory Frostfell mechanic.</li></ul><p>Do not put a three-choice interface on top of these ideas. Before an interaction, the player should be able to predict a result from the scene. After it, the result must be obvious without a toast or journal explanation.</p></div><h3>Reward plan</h3><ul><li><b>Main route:</b> story progress, combat XP and an unlocked return route. Do not award a chest for every lever.</li><li><b>Mountain mastery:</b> preserve the winter cloak and roof/camp discoveries. Signal a reward before committing to the hard branch.</li><li><b>Cave mastery:</b> retain shard opportunities in optional traversal. Keep the regional total at five; reconcile existing IDs and saved pickups before any implementation.</li><li><b>Hunting:</b> place an optional repeatable Legion camp beside a believable transport staging area. Rescue guards stay finite.</li><li><b>Rare equipment:</b> use a clearly marked, optional challenge with a fixed or appropriately weighted reward. Do not silently raise common-chest rarity rates.</li></ul>
<details><summary>Construction rules and acceptance checks</summary><ul><li>Fail a puzzle review if blind cycling is the easiest strategy, the scene cannot explain the solution, or its only visible result is a door opening. Require a before/after capture from the normal camera and a short clip of the actual interaction.</li><li>Use no mandatory order-guessing puzzle in the proposed Frostfell prototype. Do not count the heat shutter and cold shutter as two novel mechanics; one teaches the spatial rule and the other applies it during traversal.</li><li>These are route diagrams, not measured collision maps. Prove every jump using actual movement physics before adding detailed art.</li><li>Build terrain, sightlines and quest-critical routes first. Place NPCs and write final dialogue after those routes work.</li><li>Every prop needs a reason: structure, work, habitation, guidance or story evidence. Avoid evenly scattered filler. Give each station a coherent footprint.</li><li>Keep one clear landmark visible at each major decision. An objective arrow is assistance, not a substitute for legible terrain.</li><li>The crossing must be necessary for the intended route. No accidental adjacent staircase may invalidate it.</li><li>Test failures: missed jump, wrong water state, death after rescue, reload during progress and a second player arriving late. No lost Ellis, unreachable item, repeated rewards or permanent lock.</li><li>Check all camera modes, ceilings, floor fading and enemy navigation at narrow passages. No walkable floor should disappear beneath the player.</li><li>Keep scenario flags and shard IDs compatible with saves. Changes to geometry must relocate checkpoint positions safely.</li><li>Record completion time, wrong turns, idle travel, repeated instructions and optional discoveries. Human feedback decides pacing; do not claim a target duration from map size.</li><li>Only after the Keep playtest: approve this route, build a separate graybox, test movement/quests, then add art. Current campaign remains intact until replacement passes.</li></ul></details></section>
<h2>Verification limits</h2><p>All 16 areas were loaded through the actual game in a disposable browser state. Initial coordinates were finite for inspected segments, obstacles, walls, NPCs, story objects and enemies. Source files and hashes are recorded in the repository. This is not a complete playthrough, collision proof, quest-completion test or performance benchmark.</p><p>The runtime <code>ZONES.side</code> metadata contains legacy trial names and is not used here to decide class unlock placement. Implementation must follow the active Rift Hall mapping. This review does not canonize new class assignments.</p><p><a href="/3d/">Return to Bladefall</a></p>'''

def diagram(title,nodes,edges,filename):
    colors={'main':'#efc777','side':'#91dbe8','fight':'#ef9490'}
    svg=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 810" role="img">',f'<title>{esc(title)}</title>', '<rect width="960" height="810" fill="#14232e"/>',f'<text x="34" y="48" fill="#f3ca83" font-size="27" font-family="sans-serif">{esc(title)}</text>', '<text x="34" y="77" fill="#bdcbd5" font-size="16" font-family="sans-serif">Schematic only · solid = main route · dashed = optional loop · not to scale</text>']
    for a,b,kind in edges:
        x,y,*_=nodes[a];xx,yy,*_=nodes[b]
        svg.append(f'<path d="M{x},{y} L{xx},{yy}" fill="none" stroke="{colors[kind]}" stroke-width="5" '+('stroke-dasharray="12 9" ' if kind=='side' else '')+'/>')
    for x,y,label,sub,kind in nodes:
        svg.append(f'<rect x="{x-116}" y="{y-39}" width="232" height="78" rx="13" fill="#203544" stroke="{colors[kind]}" stroke-width="2"/><text x="{x}" y="{y-5}" fill="#fff" text-anchor="middle" font-size="18" font-family="sans-serif">{esc(label)}</text><text x="{x}" y="{y+21}" fill="#c7d8e3" text-anchor="middle" font-size="14" font-family="sans-serif">{esc(sub)}</text>')
    svg.append('<text x="34" y="784" fill="#bdcbd5" font-size="16" font-family="sans-serif">Read upward from START. Physical heights and distances await movement testing.</text></svg>')
    (DOC/filename).write_text(''.join(svg),encoding='utf-8')

diagram('Frostfell 1 · Snowbound Peaks',[
 (470,695,'START · Mountain foot','See the distant cave','main'),(470,575,'Heath’s shelter','Rest + frozen winch in view','main'),(470,445,'Crossing winch','Heat brake → open crossing','main'),(470,315,'Wind traverse','Cover → jump → catch ledge','main'),(470,195,'Signal crown','Align visible reflector','main'),(770,140,'Cave approach','Transport patrol → Part 2','fight'),(155,570,'Old lift house','Optional roof challenge','side'),(155,405,'Buried camp','Cloak / discovery','side'),(770,400,'High ledge','Optional difficult shard route','side')],[(0,1,'main'),(1,2,'main'),(2,3,'main'),(3,4,'main'),(4,5,'main'),(1,6,'side'),(6,7,'side'),(7,2,'side'),(3,8,'side'),(8,4,'side')],'peaks.svg')
diagram('Frostfell 2 · Deep Ice Caves',[
 (470,695,'START · Overlook','See laboratory + far exit','main'),(470,570,'Laboratory rescue','Interrupt Ellis’s transfer','fight'),(470,450,'Confiscated records','Recover while moving forward','main'),(470,330,'Water basin','Move channel → ride platform','main'),(470,205,'Cold-air shutter','Aim freezing area → cross','main'),(770,145,'Officer exit','Three coordinated opponents','fight'),(155,500,'Hugo’s shelf','Optional rope rescue','side'),(155,340,'Safe landing','Rescue route rejoins here','side'),(770,360,'Chiller branch','Optional harder discovery','side')],[(0,1,'main'),(1,2,'main'),(2,3,'main'),(3,4,'main'),(4,5,'main'),(2,6,'side'),(6,7,'side'),(7,3,'side'),(3,8,'side'),(8,4,'side')],'caves.svg')
page='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bladefall · Campaign design review</title><style>'+CSS+'</style></head><body><main>'+INTRO+cards+PLAN+'</main></body></html>'
(DOC/'index.html').write_text(page,encoding='utf-8')
for name in ['index.html','peaks.svg','caves.svg']:
    (PUB/name).write_bytes((DOC/name).read_bytes())
print('Built review for 16 areas, two Frostfell maps; no invalid initial coordinates found.')
