async page=>{
const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4331/3d/?mute=1');await page.waitForFunction(()=>window.__BF3&&HERO3D?.ready);await page.evaluate(async()=>{const b=__BF3;await b.briarReady;b.loadMode('rl');b.meta.run=null;b.meta.bank=null;b.meta.introSeen=true;b.meta.classId='warrior';b.meta.autoAttack=false;b.meta.petActive=null;b.meta.riftShards=['RK-01','RK-02','RK-03','RK-04','RK-05'];b.openHub();b.enterZone(2);b.nextArea();b.nextArea();b.meta.tutOff=true;b.G.p.invuln=999;});await page.waitForFunction(()=>!BF_LOADING.active&&__world3d().counts.keepArt);await page.waitForTimeout(350);
const result=await page.evaluate(()=>{const b=__BF3,G=b.G,e=G.boss,p=G.p,checks=[],ok=(n,v)=>{if(!v)throw Error(n);checks.push(n)},tick=n=>{for(let i=0;i<n;i++)b.update(.016);};ok('campaign uses solo human-sized champion',e.fallenDuel&&e.h===58&&G.enemies.length===1);ok('no hazard tiles or reinforcements',!G.haz&&!G.trails.length&&!G.shockwaves.length);e.active=true;e.stunT=999;
const points=[[0,600],[450,600],[450,0],[650,0],[450,0],[450,-600],[0,-600],[-450,-600],[-450,0],[-650,0],[-450,0],[-450,600],[0,600],[0,0],[0,-600]],failed=[];let samples=0;for(let k=1;k<points.length;k++){const from=points[k-1],to=points[k],steps=Math.ceil(Math.hypot(to[0]-from[0],to[1]-from[1])/70);for(let j=1;j<=steps;j++){const x=from[0]+(to[0]-from[0])*j/steps,z=from[1]+(to[1]-from[1])*j/steps;for(let i=0;i<150;i++){const dx=x-p.x,dz=z-p.z,d=Math.hypot(dx,dz);if(d<14)break;b.input.jx=dx/d;b.input.jz=dz/d;b.update(.016);}samples++;if(Math.hypot(p.x-x,p.z-z)>25||Math.abs(p.y)>10)failed.push({x,z,p:[p.x,p.z,p.y]});}}b.input.jx=b.input.jz=0;ok('connected hall and both alcoves traverse',!failed.length);
e.stunT=0;Object.assign(e,{x:0,z:0,fallState:'thrust',fallClock:1.05,fallKind:'thrust',fallSeq:0});Object.assign(p,{x:0,z:300,y:0});tick(29);const dx=e.fallDX,dz=e.fallDZ;Object.assign(p,{x:300,z:300});tick(20);ok('thrust aim stays locked',e.fallDX===dx&&e.fallDZ===dz);tick(45);ok('real fight produces recovery window',e.fallState==='recover'||e.fallState==='hunt');
Object.assign(e,{x:-220,z:0,fallState:'thrust',fallClock:1.05,fallKind:'thrust'});Object.assign(p,{x:-220,z:-500,y:0});tick(90);ok('pillar stops thrust with extra recovery',e.fallState==='stagger'&&e.z>-170);
Object.assign(e,{x:0,z:0,fallState:'strike',fallClock:.32,fallAttack:.32,fallKind:'sweep',fallSeq:99,fallX:0,fallZ:0,fallDX:0,fallDZ:1});Object.assign(p,{x:0,z:100,y:0,invuln:0,dodgeTimer:0,hp:10000});const hp=p.hp;tick(1);ok('active sword hit damages player',p.hp<hp);const hit=p.hp;p.invuln=0;tick(1);ok('same attack cannot hit twice',p.hp===hit);
Object.assign(e,{fallState:'strike',fallClock:.32,fallAttack:.32,fallSeq:100});p.dodgeTimer=.3;p.invuln=0;const dodgeHP=p.hp;b.updateBoss(e,.016,p,0,1,100,100);ok('dodge avoids sword damage',p.hp===dodgeHP);
b.meta.classId='bladedancer';p.dodgeTimer=0;p.invuln=0;p.bdParryT=1;p.bdRiposte=0;e.fallSeq=101;e.fallAttack=.32;const parryHP=p.hp;b.updateBoss(e,.016,p,0,1,100,100);ok('class parry catches sword and stores riposte',p.hp===parryHP&&p.bdRiposte===1);b.meta.classId='warrior';e.hp=e.maxHp*.4;p.invuln=999;tick(800);ok('phase two keeps solo fight without crystals',G.enemies.length===1&&!e.shielded);e.hp=0;b.killEnemy(e);ok('death opens release exit and north journal clue',!!G.portal&&!!G.storyState.notes['keep.north']);ok('all banked shards retained',b.meta.riftShards.length===5);return {checks,samples,failed,counts:__world3d().counts};});if(errors.length)throw Error(JSON.stringify(errors));return {...result,errors};
}
